VitaBrevis/VitaBrevis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('rest_juegos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VitaBrevis/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from .views import inicio, registrarPerfil, usuario, registro, administrador,anadirjuego,listajuegos,registrarjuego,eliminarJuego,edicionJuegos,editarjuego,inicios,Juego,Categorias,Usuarios,eliminarUsuario,anadirPerfil,registrarPerfil,edicionPerfil,editarPerfil,compra

urlpatterns = [
    path('', inicio,name="Principal"),
    path('usuario', usuario,name="usuario"),
    path('administrador',administrador,name='administrador'),
    path('anadirjuego',anadirjuego,name='anadirjuego'),
    path('listajuegos',listajuegos,name='listajuegos'),
    path('registrarjuego/',registrarjuego,name='registrarjuego'),
    path('registrarPerfil/',registrarPerfil,name='registrarPerfil'),
    path('eliminarJuego/<codigo>',eliminarJuego,name='eliminarJuego'),
    path('edicionJuegos/<codigo>',edicionJuegos,name='edicionJuegos'),
    path('editarjuego/',editarjuego,name='editarjuego'),
    path('editarPerf/',editarPerfil,name='editarPerfil'),
    path('inicio',inicios,name="inicio"),
    path('Juegos/<codigo>',Juego,name='Juego'),
    path('Categoria/<nombreCategoria>',Categorias,name='Juego'),
    path('listaUsuarios',Usuarios,name='listaUsuarios'),
    path('eliminarUsuario/<id>',eliminarUsuario,name='eliminarUsuario'),
    path('anadirPerfil',anadirPerfil,name='anadirPerfil'),
    path('editarPerfil',edicionPerfil,name='edicionPerfil'),
    path('compra/<int:valor>/',compra,name='compra'),


    path('registro', registro,name="registro"),
    path('login/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='core/logout.html'), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VitaBrevis/core/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    codigo = models.IntegerField(primary_key=True, verbose_name='Codigo de la Categoria')
    nombreCategoria = models.CharField(max_length=20, verbose_name='Categoria', blank=False, null=False)

    def __str__(self):
        return self.nombreCategoria


class Producto(models.Model):
    codigo = models.CharField(primary_key=True, max_length=6)
    nombre = models.CharField(max_length=50)
    precio = models.PositiveSmallIntegerField()
    video = models.CharField(max_length=150,null=True)
    foto = models.ImageField(upload_to="juegos", null= True)
    descripcion = models.TextField(null=True)
    stock = models.PositiveSmallIntegerField(null=True)
    masInfo1 = models.TextField(blank=True,null=True,verbose_name = 'Mas Informacion del Juego 1')
    masInfo2 = models.TextField(blank=True,null=True,verbose_name = 'Mas Informacion del Juego 2')
    masInfo3 = models.TextField(blank=True,null=True,verbose_name = 'Mas Informacion del Juego 3')
    masInfo4 = models.TextField(blank=True,null=True,verbose_name = 'Mas Informacion del Juego 4')
    masInfo5 = models.TextField(blank=True,null=True,verbose_name = 'Mas Informacion del Juego 5')
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE,null=True)

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.codigo)

class Perfil(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,null=True)
    imagen = models.ImageField(upload_to="juegos", null= True)
    descripcion = models.TextField(null=True,blank=True)
    edad = models.PositiveSmallIntegerField(null=True,blank=True)
    nombre = models.CharField(max_length=150,null=True,blank = True)
    apellido = models.CharField(max_length=150,null=True,blank = True)
    pais = models.TextField(null=True,blank=True)
    estado = models.TextField(null=True,blank=True)

VitaBrevis/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()
	password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
		help_texts = {k:"" for k in fields }

VitaBrevis/core/views.py
from django.shortcuts import render, redirect
from .models import Categoria, Producto , Perfil
from .forms import UserRegisterForm
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.

def inicio(request):
    Productos = Producto.objects.all()
    Categorias= Categoria.objects.all()
    perfil = Perfil.objects.all()
    contexto = {
        "Productos" : Productos,
        "categoria" : Categorias,
        "Perfil" : perfil
    }
    return render(request,'core/Principal.html', contexto)


def compra(request, valor):
    Productos =  Producto.objects.get(precio=valor)
    Categorias= Categoria.objects.all()
    perfil = Perfil.objects.all()
    total = round(valor /800) 
    contexto = {
        "Productos" : Productos,
        "categoria" : Categorias,
        "Perfil" : perfil,
        "valor_producto": valor,
        "total": total
    }
    return render(request,'core/compra.html', contexto)
def PS5(request):
    return render(request,'core/PS5.html')

def registro(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			messages.success(request, f'Usuario {username} creado')
			return redirect('login')
	else:
		form = UserRegisterForm()

	context = { 'form' : form }
	return render(request, 'core/registro.html', context)

def login(request):
    return render(request,'core/inicio.html')

def usuario(request):
    categorias= Categoria.objects.all()
    return render(request,'core/usuarios.html',{"cate":categorias})


def logout(request):
    return render(request,'core/logout.html')

def Usuarios(request):
    categorias= User.objects.all() #me trae todos los registros de esa tabla (select * from)
    return render(request,'core/listaUsuarios.html',{"usuario":categorias})

def eliminarUsuario(request, id):
    produc = User.objects.get(id=id)
    produc.delete()
    messages.success(request,'Usuario Eliminado')
    return redirect('listaUsuarios')

def Categorias(request,nombreCategoria):
    categorias= Categoria.objects.get(nombreCategoria=nombreCategoria)
    Productos = Producto.objects.all()
    cate = Categoria.objects.all()
    contexto = {
        "Productos" : Productos,
        "categoria" : categorias,
        "cate" : cate
    }
    return render(request,'core/Categoria.html',contexto)

def administrador(request):
    Productos = Producto.objects.all()
    categoria = Categoria.objects.all()
    users = User.objects.all()
    perfil = Perfil.objects.all() 
    contexto = {
        "Productos" : Productos,
        "categoria" : categoria,
        "usuarios" : users,
        "perfil" : perfil
    }
    return render(request,'core/administrador.html',contexto) 

def inicios(request):
    Productos = Producto.objects.all()
    Categorias= Categoria.objects.all()
    contexto = {
        "Productos" : Productos,
        "categoria" : Categorias
    }
    return render(request,'core/inicio.html',contexto)

def anadirjuego(request):
    categorias = Categoria.objects.all() #me trae todos los registros de esa tabla (select * from)
    contexto = {"categoria_m":categorias}
    return render(request,'core/anadirjuego.html',contexto)

def anadirPerfil(request):
    usuario = User.objects.all() #me trae todos los registros de esa tabla (select * from)
    contexto = {"usuario":usuario}
    return render(request,'core/editarPerfil.html',contexto)

def Juego(request, codigo):
    producto = Producto.objects.get(codigo=codigo)
    cate = Categoria.objects.all()
    contexto = {
        "produc" : producto,
        "cate" : cate
    }
    return render(request,'core/Juegos.html',contexto)

def listajuegos(request):
    Productos = Producto.objects.all()
    return render(request,'core/listajuegos.html',{"Productos": Productos})

def listar_Categoria(request):
    categorias = Categoria.objects.all() #me trae todos los registros de esa tabla (select * from)
    return render(request,'core/anadirjuego.html',{"categoria_m":categorias})

def anadirPerfil(request):
    usuario = User.objects.all() #me trae todos los registros de esa tabla (select * from)
    contexto = {"usuario":usuario}
    return render(request,'core/anadirPerfil.html',contexto)


def registrarPerfil(request):
    user = request.POST['txtCodigo']
    f = request.FILES['file']
    descripcion = request.POST['txtDescripcion']
    edad = request.POST['txtEdad']
    nombre = request.POST['txtNombre']
    apellido = request.POST['txtApellido']
    pais = request.POST['pais']
    sexo = request.POST['Sexo']
    

    Perfil.objects.create(imagen=f,descripcion=descripcion ,user_id=user,apellido=apellido, edad=edad ,  estado=sexo, nombre=nombre,   pais=pais )
    messages.success(request,'Perfil Registrado')
    return redirect('usuario')

def registrarjuego(request):
    codigo = request.POST['txtCodigo']
    nombre = request.POST['txtNombre']
    precio = request.POST['txtPrecio']
    categoria_m = request.POST['categoria']
    stock = request.POST['txtStock']
    f = request.FILES['file']
    video = request.POST['txtVideo']
    descripcion = request.POST['txtDescripcion']
    masInfo1 = request.POST['txtMasInfo1']
    masInfo2 = request.POST['txtMasInfo2']
    masInfo3 = request.POST['txtMasInfo3']
    masInfo4 = request.POST['txtMasInfo4']
    masInfo5 = request.POST['txtMasInfo5']
    categoria_c = Categoria.objects.get(codigo = categoria_m)

    Producto.objects.create(codigo=codigo, nombre=nombre, precio=precio, categoria=categoria_c, stock=stock, foto=f, video=video, descripcion=descripcion, masInfo1=masInfo1, masInfo2=masInfo2, masInfo3=masInfo3, masInfo4=masInfo4, masInfo5=masInfo5)
    messages.success(request,'Juego Registrado')
    return redirect('listajuegos')

def eliminarJuego(request, codigo):
    produc = Producto.objects.get(codigo=codigo)
    produc.delete()
    messages.success(request,'Juego Eliminado')
    return redirect('listajuegos')
    
def edicionJuegos(request, codigo):
    producto = Producto.objects.get(codigo=codigo)
    categorias = Categoria.objects.all()
    contexto = {
        "produc" : producto,
        "categoria" : categorias
    }
    return render(request,"core/edicionJuegos.html",contexto)

def edicionPerfil(request):
    usuario = User.objects.all() #me trae todos los registros de esa tabla (select * from)
    contexto = {"usuario":usuario}
    return render(request,'core/editarPerfil.html',contexto)


def editarPerfil(request):
    user = request.POST['txtCodigo']
    descripcion = request.POST['txtDescripcion']
    edad = request.POST['txtEdad']
    nombre = request.POST['txtNombre']
    apellido = request.POST['txtApellido']
    pais = request.POST['pais']
    sexo = request.POST['Sexo']
    produc = Perfil.objects.get(user_id=user)
    if(request.FILES.get("file")):
        f = request.FILES["file"]
        produc.imagen = f


    produc.user_id = user
    produc.nombre = nombre
    produc.apellido = apellido
    produc.edad = edad
    produc.estado = sexo
    produc.descripcion = descripcion
    produc.pais = pais
    produc.save()
    messages.success(request,'Perfil editado')
    return redirect('usuario')

def edicionJuegos(request, codigo):
    producto = Producto.objects.get(codigo=codigo)
    categorias = Categoria.objects.all()
    contexto = {
        "produc" : producto,
        "categoria" : categorias
    }
    return render(request,"core/edicionJuegos.html",contexto)

def editarjuego(request):
    codigo = request.POST['txtCodigo']
    nombre = request.POST['txtNombre']
    precio = request.POST['txtPrecio']
    stock = request.POST['txtStock']
    categoria_m = request.POST['categoria']
    video = request.POST['txtVideo']
    descripcion = request.POST['txtDescripcion']
    masInfo1 = request.POST['txtMasInfo1']
    masInfo2 = request.POST['txtMasInfo2']
    masInfo3 = request.POST['txtMasInfo3']
    masInfo4 = request.POST['txtMasInfo4']
    masInfo5 = request.POST['txtMasInfo5']
    produc = Producto.objects.get(codigo=codigo)
    if(request.FILES.get("file")):
        f = request.FILES["file"]
        produc.foto = f


    produc.codigo = codigo
    produc.nombre = nombre
    produc.precio = precio
    produc.stock = stock
    produc.video = video
    produc.descripcion = descripcion
    produc.masInfo1 = masInfo1
    produc.masInfo2 = masInfo2
    produc.masInfo3 = masInfo3
    produc.masInfo4 = masInfo4
    produc.masInfo5 = masInfo5
    categoria_c = Categoria.objects.get(codigo = categoria_m)
    produc.categoria = categoria_c
    produc.save()
    messages.success(request,'Juego Editado')
    return redirect('listajuegos')


VitaBrevis/core/templates/core/Juegos.html
{% extends 'core/PlantillaJuegos.html' %}

{% block categ %}
{% for c in cate %}
<li><a class="dropdown-item" href="http://127.0.0.1:8000/Categoria/{{c.nombreCategoria}}">{{c.nombreCategoria}}</a></li>
{% endfor %}
{% endblock %}


{% load static %}

{% block Imagen %}
    {% if produc.foto %}
        <img class="card-img-top" src="{{ produc.foto.url }}"  alt="Card image" >
    {% else %}
    <p style="text-align: center; margin-top: 235px;">No posee Imagen</p>
    {% endif %}
{% endblock Imagen %}

{% block Nombre %}
<h4>{{produc.nombre}}</h4>
{% endblock Nombre %}

{% block Descripcion %}
<p>{{produc.descripcion}}</p>
{% endblock Descripcion %}

{% block Precio %}
<h3>CLP ${{produc.precio}}</h3>
{% endblock Precio %}

{% block Comprar %}
<a href="{% url 'compra' valor=produc.precio %}" style="width: 150px;" class="btn btn-outline-light">Comprar</a>
{% endblock Comprar %}
{% block Video %}
<iframe src= {{produc.video}} title="YouTube video" allowfullscreen></iframe>
{% endblock Video %}


{% block Info1 %}
<li>{{produc.masInfo1}}</li>
{% endblock Info1 %}

{% block Info2 %}
<li>{{produc.masInfo2}}</li>
{% endblock Info2 %}

{% block Info3 %}
<li>{{produc.masInfo3}}</li>
{% endblock Info3 %}

{% block Info4 %}
<li>{{produc.masInfo4}}</li>
{% endblock Info4 %}

VitaBrevis/core/templates/core/Plantillaregistro.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}">
    <link href="{% static 'core/css/variable.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'core/css/estilos2.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/style2.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/normalize.css' %}">
    <link rel="shortcut icon" href="{% static 'core/img/icono-game.png' %}" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!--google material icon-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp">
    <title>Registro</title>
</head>

<script src="https://kit.fontawesome.com/19e0713a59.js" crossorigin="anonymous"></script>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href=""><img src="{% static 'core/img/icono-game.png' %}" width="70" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'Principal' %}">Inicio</a>
                    </li>
                        
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Registro/inicio
                        </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'registro' %}">Registrate</a></li>
                        <li><a class="dropdown-item" href="{% url 'login' %}">Iniciar sesion</a></li>
                    </ul>
                    <li class="nav-item">
                        <div class="theme-toggler">
                            <span class="material-icons-sharp active">dark_mode</span>
                            <span class="material-icons-sharp ">light_mode</span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
		{% for message in messages %}
		<div class="notification {{ message.tags}}">
			{{ message }}
		</div>
		{% endfor %}
    {% endif %}

    {% block contenido %}
    {% endblock %}
<!-- no tocar-->
<footer class="pie-pagina">
    <div class="grupo-1">
        <div class="box">
        <figure>
            <a href="#">
            <img src="{% static 'core/img/icono-game.png' %}" alt="icono de la pagina">
            </a>
        </figure>
        </div>
        <div class="box">
        <H2>UBICANOS EN:</H2>
        <div id="map" style="margin: auto;"></div>
        </div>
        
        <div class="box">
        <h2>SIGUENOS EN:</h2>
        <div class="red-social">
            <a href="https://www.facebook.com/manuelalejandro.collaocontreras" target="_blank" class="fa fa-facebook"></a>
            <a href="https://www.instagram.com/haronzhuxetumare/?hl=es" target="_blank" class="fa fa-instagram"></a>
            <a href="https://twitter.com/IbaiLlanos" target="_blank" class="fa fa-twitter"></a>
            <a href="https://www.youtube.com/channel/UCeeR24qo3BpK115JfzNGflw" target="_blank" class="fa fa-youtube"></a>
        </div>
        <div class="box" style="margin-top: 8px;">
            <h2>Sobre nosotros:</h2>
            <p>Somos una pagina la cual vende juegos a un precio mas razonable de lo que las puedes encontrar en cualquier otro sitio.</p>
            <p>Somos 2 alumnos de Ingenieria en Informática .</p>
        </div>
    </div>
    </div>
    <div class="grupo-2">
        <small>&copy; 2022 <b>Game4Ever</b> - Todos los Derechos Reservados</small>
    </div>
</footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/valid.js' %}"></script>
    <script src="{% static 'core/js/script.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCJiBdUqpAFEjiHSFVqWt-uBfkPeioang&callback=iniciarMap"></script>
    <script src="{% static 'core/js/cambiocolor.js'%}"></script>
    </body>
</html>

VitaBrevis/core/templates/core/inicio.html
{% extends "./plantilla_inicio.html" %}

{% block cate %}
{% for c in Productos %}
<li><a class="dropdown-item" href="accion">{{c.categoria.nombreCategoria}}</a></li>    
{% endfor %}     
{% endblock %}

{% block categ %}
{% for c in categoria %}
<li><a class="dropdown-item" href="Categoria/{{c.nombreCategoria}}">{{c.nombreCategoria}}</a></li>
{% endfor %}
{% endblock %}

{% block body %}
{% for c in Productos %}
    <div class="card-ini" > <a href="Juegos/{{c.codigo}}" class="imagen12" >
      {% if c.foto %}
        <img class="card-img-top" src="{{ c.foto.url }}"  alt="Card image" >
      {% else %}
      <p style="text-align: center; margin-top: 235px;">No posee Imagen</p>
      {% endif %}</a>
          <div class="card-body"> 
          <h6 class="card-title">{{ c.nombre }} <br>CLP ${{ c.precio }}</h6>
        </div>
      </div>
{% endfor %}

{% endblock %}

VitaBrevis/core/templates/core/plantillacategoria.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'core/css/variable.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{% static 'core/img/icono-game.png' %}" type="image/x-icon">
    <!--google material icon-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp">
    <title>{% block titulo %} 
      {% endblock %}</title>
</head>
<script src="https://kit.fontawesome.com/19e0713a59.js" crossorigin="anonymous"></script>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href=""><img src="{% static 'core/img/icono-game.png' %}" width="70" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/inicio">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categorias
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% block categ %}
                      {% endblock %}
                    </ul>
                    {% if perms.core.add_producto %}
                <li class="nav-item">
                  <li><a class="nav-link fondoletrasmenu" href="{% url 'administrador' %}">Administracion </a></li>
                </li>
                <li class="nav-item">
                  <li><a class="nav-link fondoletrasmenu" href="{% url 'usuario' %}">{{ user.username }}</a></li>
                </li>
                
              {% elif user.is_authenticated %}
                <li class="nav-item">
                  <li><a class="nav-link fondoletrasmenu" href="{% url 'usuario' %}">{{ user.username }}</a></li>
                </li>
                {% else %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Registro/Inicio
                    </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/registro">Registrate</a></li>
                    <li><a class="dropdown-item" href="http://127.0.0.1:8000/login/">Iniciar sesion</a></li>
                  </ul>
              {% endif %}
              <li class="nav-item">
                <div class="theme-toggler">
                    <span class="material-icons-sharp active">dark_mode</span>
                    <span class="material-icons-sharp ">light_mode</span>
                </div>
            </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>{% block categoria %} 
        {% endblock %}
    </h1>
    <!-- Fila 1 -->
    <section class="juegos">
        <section class="juegos">
            <div class="container">
            <div class="galeria-port">
    {% block body %}
    {% endblock %}
    
    </section>
    
    

</div>

<!-- no tocar-->
</div>
<footer class="pie-pagina">
  <div class="grupo-1">
    <div class="box">
      <figure>
        <a href="#">
          <img src="{% static 'core/img/icono-game.png' %}" alt="icono de la pagina">
        </a>
      </figure>
    </div>
    <div class="box">
      <h2>SOBRE NOSOTROS</h2>
      <p>Somos una pagina la cual vende juegos a un precio mas razonable de lo que las puedes encontrar en cualquier otro sitio.</p>
      <p>Somos 2 alumnos de Ingenieria en Informática .</p>
    </div>
    <div class="box">
      <h2>SIGUENOS EN:</h2>
      <div class="red-social">
        <a href="https://www.facebook.com/manuelalejandro.collaocontreras" target="_blank" class="fa fa-facebook"></a>
        <a href="https://www.instagram.com/haronzhuxetumare/?hl=es" target="_blank" class="fa fa-instagram"></a>
        <a href="https://twitter.com/IbaiLlanos" target="_blank" class="fa fa-twitter"></a>
        <a href="https://www.youtube.com/channel/UCeeR24qo3BpK115JfzNGflw" target="_blank" class="fa fa-youtube"></a>
      </div>
    </div>
  </div>
  <div class="grupo-2">
    <small>&copy; 2022 <b>Game4Ever</b> - Todos los Derechos Reservados</small>
  </div>
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/cambiocolor.js'%}"></script>
</body>
</html>